# -*- coding: utf-8 -*-
"""M420CQ.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xIFn7soQcQvQl9XLr6WP17-zDhEN4qz8

# **Data Load**
"""

import zipfile
import os

zip_path = "/content/classification_task.zip"
extract_path = "/content/dataset"

with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall(extract_path)

print("Dataset extracted to:", extract_path)

for root, dirs, files in os.walk("/content/dataset"):
    print(root)

"""# **Import all libraries**"""

import os
import numpy as np
import tensorflow as tf
import matplotlib.pyplot as plt
import random
from tensorflow.keras.preprocessing.image import load_img

from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.applications import MobileNetV2, ResNet50
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Dense, GlobalAveragePooling2D, Dropout

from sklearn.metrics import classification_report, confusion_matrix
import seaborn as sns

train_dir = "/content/dataset/classification_task/train"
test_dir = "/content/dataset/classification_task/test"

"""## **Image Visuals**"""

classes = os.listdir(train_dir)

image_paths = []
labels = []

for cls in classes:
    class_path = os.path.join(train_dir, cls)
    for img_name in os.listdir(class_path):
        image_paths.append(os.path.join(class_path, img_name))
        labels.append(cls)

random_indices = random.sample(range(len(image_paths)), 10)

plt.figure(figsize=(12, 10))

for i, idx in enumerate(random_indices):
    img = load_img(image_paths[idx], target_size=(224, 224))

    plt.subplot(2, 5, i+1)
    plt.imshow(img)
    plt.title(labels[idx])
    plt.axis('off')

plt.tight_layout()
plt.show()

"""# **Data preprocessing**"""

IMG_SIZE = (224, 224)
BATCH_SIZE = 32

train_datagen = ImageDataGenerator(
    rescale=1./255,
    rotation_range=20,
    zoom_range=0.2,
    horizontal_flip=True
)

test_datagen = ImageDataGenerator(rescale=1./255)

train_data = train_datagen.flow_from_directory(
    train_dir,
    target_size=IMG_SIZE,
    batch_size=BATCH_SIZE,
    class_mode='categorical'
)

test_data = test_datagen.flow_from_directory(
    test_dir,
    target_size=IMG_SIZE,
    batch_size=BATCH_SIZE,
    class_mode='categorical',
    shuffle=False
)

class_names = list(train_data.class_indices.keys())
print("Classes:", class_names)

"""# **MODEL 1 — MobileNetV2**"""

base_model = MobileNetV2(weights='imagenet', include_top=False, input_shape=(224,224,3))

for layer in base_model.layers:
    layer.trainable = False

x = base_model.output
x = GlobalAveragePooling2D()(x)
x = Dense(128, activation='relu')(x)
x = Dropout(0.5)(x)
predictions = Dense(4, activation='softmax')(x)

mobilenet_model = Model(inputs=base_model.input, outputs=predictions)

mobilenet_model.compile(
    optimizer='adam',
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

mobilenet_model.summary()

history_mobilenet = mobilenet_model.fit(
    train_data,
    validation_data=test_data,
    epochs=5
)

"""# **MODEL 2 — ResNet50**"""

base_model = ResNet50(weights='imagenet', include_top=False, input_shape=(224,224,3))

for layer in base_model.layers:
    layer.trainable = False

x = base_model.output
x = GlobalAveragePooling2D()(x)
x = Dense(128, activation='relu')(x)
x = Dropout(0.5)(x)
predictions = Dense(4, activation='softmax')(x)

resnet_model = Model(inputs=base_model.input, outputs=predictions)

resnet_model.compile(
    optimizer='adam',
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

resnet_model.summary()

history_resnet = resnet_model.fit(
    train_data,
    validation_data=test_data,
    epochs=5
)

"""# **Evaluation Function**"""

def evaluate_model(model, test_data, class_names):
    predictions = model.predict(test_data)
    y_pred = np.argmax(predictions, axis=1)
    y_true = test_data.classes

    print("\nClassification Report:\n")
    print(classification_report(y_true, y_pred, target_names=class_names))

    cm = confusion_matrix(y_true, y_pred)

    plt.figure(figsize=(6,5))
    sns.heatmap(cm, annot=True, fmt='d', xticklabels=class_names, yticklabels=class_names)
    plt.xlabel("Predicted")
    plt.ylabel("Actual")
    plt.title("Confusion Matrix")
    plt.show()

"""## **MobileNetV2 Results**"""

print("=== MobileNetV2 Evaluation ===")
evaluate_model(mobilenet_model, test_data, class_names)

"""## **ResNet50 Results**"""

print("=== ResNet50 Evaluation ===")
evaluate_model(resnet_model, test_data, class_names)

"""## **Accuracy Comparison Plot**"""

plt.plot(history_mobilenet.history['val_accuracy'], label='MobileNetV2')
plt.plot(history_resnet.history['val_accuracy'], label='ResNet50')
plt.legend()
plt.title("Model Comparison")
plt.xlabel("Epochs")
plt.ylabel("Validation Accuracy")
plt.show()

"""# **Prediction**"""

import numpy as np
from tensorflow.keras.preprocessing import image

img_path = "/content/dataset/classification_task/test/meningioma/brisc2025_test_00465_me_co_t1.jpg"   # <-- change this

class_names = ['glioma', 'meningioma', 'no_tumor', 'pituitary']

img = image.load_img(img_path, target_size=(224, 224))
img_array = image.img_to_array(img)
img_array = img_array / 255.0
img_array = np.expand_dims(img_array, axis=0)


prediction = resnet_model.predict(img_array)


predicted_index = np.argmax(prediction)
predicted_label = class_names[predicted_index]
confidence = np.max(prediction)


print("Predicted Class:", predicted_label)
print("Confidence:", round(confidence * 100, 2), "%")


plt.imshow(img)
plt.title(f"{predicted_label} ({confidence*100:.2f}%)")
plt.axis('off')
plt.show()

